/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAirlineCoin } from './IAirlineCoin.js';
export type { IAirlineRewardCoin } from './IAirlineRewardCoin.js';
export type { IStakingAirline } from './IStakingAirline.js';