/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from './interface/index.js';
export type { interface };
import type * as nfts from './nfts/index.js';
export type { nfts };
import type * as tokens from './tokens/index.js';
export type { tokens };
export type { StakingAirline } from './StakingAirline.js';