/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aircraftNftSol from './AircraftNft.sol/index.js';
export type { aircraftNftSol };
export type { LicenseNFT } from './LicenseNFT.js';