/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AirlineInterface extends Interface {
    getFunction(nameOrSignature: "MAX_PILOT_LEVEL" | "closeAirline(bytes,bytes32)" | "closeAirline()" | "getPilotLevel" | "isOpen" | "joinAirline(uint8)" | "joinAirline(address,uint8)" | "leaveAirline" | "openAirline()" | "openAirline(bytes,bytes32)" | "owner" | "pilots" | "renounceOwnership" | "totalPilots" | "totalPilotsCount" | "transferOwnership" | "updatePilotLevel"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AirlineStatusChanged" | "ExitAirlineMember" | "NewAirlineMember" | "OwnershipTransferred" | "PilotLevelUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_PILOT_LEVEL', values?: undefined): string;
encodeFunctionData(functionFragment: 'closeAirline(bytes,bytes32)', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'closeAirline()', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPilotLevel', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isOpen', values?: undefined): string;
encodeFunctionData(functionFragment: 'joinAirline(uint8)', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'joinAirline(address,uint8)', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'leaveAirline', values?: undefined): string;
encodeFunctionData(functionFragment: 'openAirline()', values?: undefined): string;
encodeFunctionData(functionFragment: 'openAirline(bytes,bytes32)', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pilots', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalPilots', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalPilotsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePilotLevel', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MAX_PILOT_LEVEL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeAirline(bytes,bytes32)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeAirline()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPilotLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinAirline(uint8)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinAirline(address,uint8)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leaveAirline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openAirline()', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openAirline(bytes,bytes32)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pilots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPilots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalPilotsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePilotLevel', data: BytesLike): Result;
  }

  
    export namespace AirlineStatusChangedEvent {
      export type InputTuple = [isOpen: boolean];
      export type OutputTuple = [isOpen: boolean];
      export interface OutputObject {isOpen: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExitAirlineMemberEvent {
      export type InputTuple = [_pilot: AddressLike];
      export type OutputTuple = [_pilot: string];
      export interface OutputObject {_pilot: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NewAirlineMemberEvent {
      export type InputTuple = [_pilot: AddressLike, _level: BigNumberish];
      export type OutputTuple = [_pilot: string, _level: bigint];
      export interface OutputObject {_pilot: string, _level: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PilotLevelUpdatedEvent {
      export type InputTuple = [pilot: AddressLike, oldLevel: BigNumberish, newLevel: BigNumberish];
      export type OutputTuple = [pilot: string, oldLevel: bigint, newLevel: bigint];
      export interface OutputObject {pilot: string, oldLevel: bigint, newLevel: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Airline extends BaseContract {
    
    connect(runner?: ContractRunner | null): Airline;
    waitForDeployment(): Promise<this>;

    interface: AirlineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_PILOT_LEVEL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    "closeAirline(bytes,bytes32)": TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    "closeAirline()": TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getPilotLevel: TypedContractMethod<
      [_pilot: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isOpen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    "joinAirline(uint8)": TypedContractMethod<
      [_level: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    "joinAirline(address,uint8)": TypedContractMethod<
      [_pilot: AddressLike, _level: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    leaveAirline: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    "openAirline()": TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    "openAirline(bytes,bytes32)": TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pilots: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalPilots: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalPilotsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePilotLevel: TypedContractMethod<
      [_pilot: AddressLike, _newLevel: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_PILOT_LEVEL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'closeAirline(bytes,bytes32)'): TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeAirline()'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPilotLevel'): TypedContractMethod<
      [_pilot: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isOpen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'joinAirline(uint8)'): TypedContractMethod<
      [_level: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'joinAirline(address,uint8)'): TypedContractMethod<
      [_pilot: AddressLike, _level: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'leaveAirline'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openAirline()'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openAirline(bytes,bytes32)'): TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pilots'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalPilots'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalPilotsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePilotLevel'): TypedContractMethod<
      [_pilot: AddressLike, _newLevel: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AirlineStatusChanged'): TypedContractEvent<AirlineStatusChangedEvent.InputTuple, AirlineStatusChangedEvent.OutputTuple, AirlineStatusChangedEvent.OutputObject>;
getEvent(key: 'ExitAirlineMember'): TypedContractEvent<ExitAirlineMemberEvent.InputTuple, ExitAirlineMemberEvent.OutputTuple, ExitAirlineMemberEvent.OutputObject>;
getEvent(key: 'NewAirlineMember'): TypedContractEvent<NewAirlineMemberEvent.InputTuple, NewAirlineMemberEvent.OutputTuple, NewAirlineMemberEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PilotLevelUpdated'): TypedContractEvent<PilotLevelUpdatedEvent.InputTuple, PilotLevelUpdatedEvent.OutputTuple, PilotLevelUpdatedEvent.OutputObject>;

    filters: {
      
      'AirlineStatusChanged(bool)': TypedContractEvent<AirlineStatusChangedEvent.InputTuple, AirlineStatusChangedEvent.OutputTuple, AirlineStatusChangedEvent.OutputObject>;
      AirlineStatusChanged: TypedContractEvent<AirlineStatusChangedEvent.InputTuple, AirlineStatusChangedEvent.OutputTuple, AirlineStatusChangedEvent.OutputObject>;
    

      'ExitAirlineMember(address)': TypedContractEvent<ExitAirlineMemberEvent.InputTuple, ExitAirlineMemberEvent.OutputTuple, ExitAirlineMemberEvent.OutputObject>;
      ExitAirlineMember: TypedContractEvent<ExitAirlineMemberEvent.InputTuple, ExitAirlineMemberEvent.OutputTuple, ExitAirlineMemberEvent.OutputObject>;
    

      'NewAirlineMember(address,uint8)': TypedContractEvent<NewAirlineMemberEvent.InputTuple, NewAirlineMemberEvent.OutputTuple, NewAirlineMemberEvent.OutputObject>;
      NewAirlineMember: TypedContractEvent<NewAirlineMemberEvent.InputTuple, NewAirlineMemberEvent.OutputTuple, NewAirlineMemberEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PilotLevelUpdated(address,uint8,uint8)': TypedContractEvent<PilotLevelUpdatedEvent.InputTuple, PilotLevelUpdatedEvent.OutputTuple, PilotLevelUpdatedEvent.OutputObject>;
      PilotLevelUpdated: TypedContractEvent<PilotLevelUpdatedEvent.InputTuple, PilotLevelUpdatedEvent.OutputTuple, PilotLevelUpdatedEvent.OutputObject>;
    
    };
  }