/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface FlightControllerInterface extends Interface {
    getFunction(nameOrSignature: "adminAddress" | "aircraftAddress" | "airlineCoin" | "completeFlight" | "flightDetails" | "prize" | "startFlight"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FlightCompleted" | "FlightStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'adminAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'aircraftAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'airlineCoin', values?: undefined): string;
encodeFunctionData(functionFragment: 'completeFlight', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'flightDetails', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'prize', values?: undefined): string;
encodeFunctionData(functionFragment: 'startFlight', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'adminAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aircraftAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'airlineCoin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeFlight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flightDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'prize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startFlight', data: BytesLike): Result;
  }

  
    export namespace FlightCompletedEvent {
      export type InputTuple = [pilot: AddressLike, flightId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [pilot: string, flightId: bigint, amount: bigint];
      export interface OutputObject {pilot: string, flightId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FlightStartedEvent {
      export type InputTuple = [pilot: AddressLike, flightId: BigNumberish];
      export type OutputTuple = [pilot: string, flightId: bigint];
      export interface OutputObject {pilot: string, flightId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FlightController extends BaseContract {
    
    connect(runner?: ContractRunner | null): FlightController;
    waitForDeployment(): Promise<this>;

    interface: FlightControllerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    adminAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    aircraftAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    airlineCoin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    completeFlight: TypedContractMethod<
      [_pilot: AddressLike, _flightId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    flightDetails: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {id: bigint, distance: bigint, aircraftId: bigint, multiplier: bigint, startTime: bigint }],
      'view'
    >
    

    
    prize: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    startFlight: TypedContractMethod<
      [_flightId: BigNumberish, _distance: BigNumberish, _aircraftId: BigNumberish, _multiplier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'adminAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'aircraftAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'airlineCoin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'completeFlight'): TypedContractMethod<
      [_pilot: AddressLike, _flightId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'flightDetails'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {id: bigint, distance: bigint, aircraftId: bigint, multiplier: bigint, startTime: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'prize'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startFlight'): TypedContractMethod<
      [_flightId: BigNumberish, _distance: BigNumberish, _aircraftId: BigNumberish, _multiplier: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FlightCompleted'): TypedContractEvent<FlightCompletedEvent.InputTuple, FlightCompletedEvent.OutputTuple, FlightCompletedEvent.OutputObject>;
getEvent(key: 'FlightStarted'): TypedContractEvent<FlightStartedEvent.InputTuple, FlightStartedEvent.OutputTuple, FlightStartedEvent.OutputObject>;

    filters: {
      
      'FlightCompleted(address,uint256,uint256)': TypedContractEvent<FlightCompletedEvent.InputTuple, FlightCompletedEvent.OutputTuple, FlightCompletedEvent.OutputObject>;
      FlightCompleted: TypedContractEvent<FlightCompletedEvent.InputTuple, FlightCompletedEvent.OutputTuple, FlightCompletedEvent.OutputObject>;
    

      'FlightStarted(address,uint256)': TypedContractEvent<FlightStartedEvent.InputTuple, FlightStartedEvent.OutputTuple, FlightStartedEvent.OutputObject>;
      FlightStarted: TypedContractEvent<FlightStartedEvent.InputTuple, FlightStartedEvent.OutputTuple, FlightStartedEvent.OutputObject>;
    
    };
  }