/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PilotCareerInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "LEVEL_2_HOURS" | "LEVEL_3_HOURS" | "LEVEL_4_HOURS" | "PILOT_CONTROLLER_ROLE" | "getPilotLevel" | "getRoleAdmin" | "getTotalFlightTime" | "grantLicense" | "grantRole" | "hasRole" | "initPilot" | "isPilotRegistered" | "licenses" | "pilots" | "recordFlight" | "renounceRole" | "revokeRole" | "supportsInterface"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CareerInitiated" | "FlightRecorded" | "LevelUpgraded" | "LicenseIssued" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'LEVEL_2_HOURS', values?: undefined): string;
encodeFunctionData(functionFragment: 'LEVEL_3_HOURS', values?: undefined): string;
encodeFunctionData(functionFragment: 'LEVEL_4_HOURS', values?: undefined): string;
encodeFunctionData(functionFragment: 'PILOT_CONTROLLER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPilotLevel', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTotalFlightTime', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantLicense', values: [AddressLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'initPilot', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isPilotRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'licenses', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'pilots', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'recordFlight', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LEVEL_2_HOURS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LEVEL_3_HOURS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LEVEL_4_HOURS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PILOT_CONTROLLER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPilotLevel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalFlightTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantLicense', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initPilot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPilotRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'licenses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pilots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordFlight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  
    export namespace CareerInitiatedEvent {
      export type InputTuple = [pilot: AddressLike, airline: AddressLike];
      export type OutputTuple = [pilot: string, airline: string];
      export interface OutputObject {pilot: string, airline: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FlightRecordedEvent {
      export type InputTuple = [pilot: AddressLike, hoursAdded: BigNumberish, newTotal: BigNumberish];
      export type OutputTuple = [pilot: string, hoursAdded: bigint, newTotal: bigint];
      export interface OutputObject {pilot: string, hoursAdded: bigint, newTotal: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LevelUpgradedEvent {
      export type InputTuple = [pilot: AddressLike, newLevel: BigNumberish];
      export type OutputTuple = [pilot: string, newLevel: bigint];
      export interface OutputObject {pilot: string, newLevel: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LicenseIssuedEvent {
      export type InputTuple = [pilot: AddressLike, licenseId: string, expiry: BigNumberish];
      export type OutputTuple = [pilot: string, licenseId: string, expiry: bigint];
      export interface OutputObject {pilot: string, licenseId: string, expiry: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PilotCareer extends BaseContract {
    
    connect(runner?: ContractRunner | null): PilotCareer;
    waitForDeployment(): Promise<this>;

    interface: PilotCareerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LEVEL_2_HOURS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LEVEL_3_HOURS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    LEVEL_4_HOURS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PILOT_CONTROLLER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getPilotLevel: TypedContractMethod<
      [_pilot: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getTotalFlightTime: TypedContractMethod<
      [_pilot: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    grantLicense: TypedContractMethod<
      [_pilot: AddressLike, _id: string, _validityDays: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    initPilot: TypedContractMethod<
      [_pilot: AddressLike, _airline: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isPilotRegistered: TypedContractMethod<
      [_pilot: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    licenses: TypedContractMethod<
      [arg0: AddressLike, arg1: string, ],
      [[string, bigint, bigint, boolean] & {identifier: string, issueDate: bigint, expiryDate: bigint, isActive: boolean }],
      'view'
    >
    

    
    pilots: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, string, boolean] & {totalFlightHours: bigint, totalFlightsCount: bigint, lastFlightAt: bigint, level: bigint, currentAirline: string, isRegistered: boolean }],
      'view'
    >
    

    
    recordFlight: TypedContractMethod<
      [_pilot: AddressLike, _hours: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LEVEL_2_HOURS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LEVEL_3_HOURS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'LEVEL_4_HOURS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PILOT_CONTROLLER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPilotLevel'): TypedContractMethod<
      [_pilot: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalFlightTime'): TypedContractMethod<
      [_pilot: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantLicense'): TypedContractMethod<
      [_pilot: AddressLike, _id: string, _validityDays: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initPilot'): TypedContractMethod<
      [_pilot: AddressLike, _airline: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isPilotRegistered'): TypedContractMethod<
      [_pilot: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'licenses'): TypedContractMethod<
      [arg0: AddressLike, arg1: string, ],
      [[string, bigint, bigint, boolean] & {identifier: string, issueDate: bigint, expiryDate: bigint, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'pilots'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, bigint, string, boolean] & {totalFlightHours: bigint, totalFlightsCount: bigint, lastFlightAt: bigint, level: bigint, currentAirline: string, isRegistered: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'recordFlight'): TypedContractMethod<
      [_pilot: AddressLike, _hours: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CareerInitiated'): TypedContractEvent<CareerInitiatedEvent.InputTuple, CareerInitiatedEvent.OutputTuple, CareerInitiatedEvent.OutputObject>;
getEvent(key: 'FlightRecorded'): TypedContractEvent<FlightRecordedEvent.InputTuple, FlightRecordedEvent.OutputTuple, FlightRecordedEvent.OutputObject>;
getEvent(key: 'LevelUpgraded'): TypedContractEvent<LevelUpgradedEvent.InputTuple, LevelUpgradedEvent.OutputTuple, LevelUpgradedEvent.OutputObject>;
getEvent(key: 'LicenseIssued'): TypedContractEvent<LicenseIssuedEvent.InputTuple, LicenseIssuedEvent.OutputTuple, LicenseIssuedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'CareerInitiated(address,address)': TypedContractEvent<CareerInitiatedEvent.InputTuple, CareerInitiatedEvent.OutputTuple, CareerInitiatedEvent.OutputObject>;
      CareerInitiated: TypedContractEvent<CareerInitiatedEvent.InputTuple, CareerInitiatedEvent.OutputTuple, CareerInitiatedEvent.OutputObject>;
    

      'FlightRecorded(address,uint256,uint256)': TypedContractEvent<FlightRecordedEvent.InputTuple, FlightRecordedEvent.OutputTuple, FlightRecordedEvent.OutputObject>;
      FlightRecorded: TypedContractEvent<FlightRecordedEvent.InputTuple, FlightRecordedEvent.OutputTuple, FlightRecordedEvent.OutputObject>;
    

      'LevelUpgraded(address,uint8)': TypedContractEvent<LevelUpgradedEvent.InputTuple, LevelUpgradedEvent.OutputTuple, LevelUpgradedEvent.OutputObject>;
      LevelUpgraded: TypedContractEvent<LevelUpgradedEvent.InputTuple, LevelUpgradedEvent.OutputTuple, LevelUpgradedEvent.OutputObject>;
    

      'LicenseIssued(address,string,uint256)': TypedContractEvent<LicenseIssuedEvent.InputTuple, LicenseIssuedEvent.OutputTuple, LicenseIssuedEvent.OutputObject>;
      LicenseIssued: TypedContractEvent<LicenseIssuedEvent.InputTuple, LicenseIssuedEvent.OutputTuple, LicenseIssuedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }