/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as aircraftNftSol from './AircraftNft.sol/index.js';
export { LicenseNFT__factory } from './LicenseNFT__factory.js';