/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IAirline, IAirlineInterface } from "../../../core/interface/IAirline.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "signature",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "senderHash",
        "type": "bytes32"
      }
    ],
    "name": "closeAirline",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_pilot",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "_level",
        "type": "uint8"
      }
    ],
    "name": "joinAirline",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes",
        "name": "signature",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "senderHash",
        "type": "bytes32"
      }
    ],
    "name": "openAirline",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IAirline__factory {
    static readonly abi = _abi;
    static createInterface(): IAirlineInterface {
      return new Interface(_abi) as IAirlineInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IAirline {
      return new Contract(address, _abi, runner) as unknown as IAirline;
    }
  }
  