/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IAirlineInterface extends Interface {
    getFunction(nameOrSignature: "closeAirline" | "joinAirline" | "openAirline"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'closeAirline', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'joinAirline', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'openAirline', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'closeAirline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'joinAirline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openAirline', data: BytesLike): Result;
  }

  

  export interface IAirline extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAirline;
    waitForDeployment(): Promise<this>;

    interface: IAirlineInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    closeAirline: TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    joinAirline: TypedContractMethod<
      [_pilot: AddressLike, _level: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    openAirline: TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'closeAirline'): TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'joinAirline'): TypedContractMethod<
      [_pilot: AddressLike, _level: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openAirline'): TypedContractMethod<
      [signature: BytesLike, senderHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }