/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IAirlinePilotInterface extends Interface {
    getFunction(nameOrSignature: "approveRequest" | "canAccessAirline" | "getNextLicenseId" | "getPendingRequest" | "getTotalLicensesIssued" | "mintLicense" | "recordFlight" | "registerPilot" | "requestAirlineAccess"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FlightRecorded" | "LicenseGranted" | "PilotRegistered" | "RequestApproved" | "RequestCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'approveRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'canAccessAirline', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getNextLicenseId', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPendingRequest', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalLicensesIssued', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintLicense', values: [AddressLike, BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'recordFlight', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerPilot', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'requestAirlineAccess', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'approveRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canAccessAirline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNextLicenseId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalLicensesIssued', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintLicense', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordFlight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPilot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestAirlineAccess', data: BytesLike): Result;
  }

  
    export namespace FlightRecordedEvent {
      export type InputTuple = [pilot: AddressLike, flightHours: BigNumberish];
      export type OutputTuple = [pilot: string, flightHours: bigint];
      export interface OutputObject {pilot: string, flightHours: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LicenseGrantedEvent {
      export type InputTuple = [pilot: AddressLike, token: BigNumberish, licenseLevel: BigNumberish];
      export type OutputTuple = [pilot: string, token: bigint, licenseLevel: bigint];
      export interface OutputObject {pilot: string, token: bigint, licenseLevel: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PilotRegisteredEvent {
      export type InputTuple = [pilot: AddressLike, flightHours: BigNumberish];
      export type OutputTuple = [pilot: string, flightHours: bigint];
      export interface OutputObject {pilot: string, flightHours: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestApprovedEvent {
      export type InputTuple = [requestId: BigNumberish, reviewer: AddressLike];
      export type OutputTuple = [requestId: bigint, reviewer: string];
      export interface OutputObject {requestId: bigint, reviewer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestCreatedEvent {
      export type InputTuple = [pilot: AddressLike, airline: AddressLike, requestId: BigNumberish];
      export type OutputTuple = [pilot: string, airline: string, requestId: bigint];
      export interface OutputObject {pilot: string, airline: string, requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IAirlinePilot extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAirlinePilot;
    waitForDeployment(): Promise<this>;

    interface: IAirlinePilotInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    canAccessAirline: TypedContractMethod<
      [pilot: AddressLike, airline: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getNextLicenseId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPendingRequest: TypedContractMethod<
      [pilot: AddressLike, airline: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    getTotalLicensesIssued: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintLicense: TypedContractMethod<
      [pilot: AddressLike, licenseLevel: BigNumberish, tokenName: string, tokenSymbol: string, ],
      [void],
      'nonpayable'
    >
    

    
    recordFlight: TypedContractMethod<
      [pilot: AddressLike, flightHours: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerPilot: TypedContractMethod<
      [pilot: AddressLike, flightHours: BigNumberish, airline: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestAirlineAccess: TypedContractMethod<
      [pilot: AddressLike, airline: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'canAccessAirline'): TypedContractMethod<
      [pilot: AddressLike, airline: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getNextLicenseId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingRequest'): TypedContractMethod<
      [pilot: AddressLike, airline: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalLicensesIssued'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintLicense'): TypedContractMethod<
      [pilot: AddressLike, licenseLevel: BigNumberish, tokenName: string, tokenSymbol: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordFlight'): TypedContractMethod<
      [pilot: AddressLike, flightHours: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerPilot'): TypedContractMethod<
      [pilot: AddressLike, flightHours: BigNumberish, airline: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestAirlineAccess'): TypedContractMethod<
      [pilot: AddressLike, airline: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FlightRecorded'): TypedContractEvent<FlightRecordedEvent.InputTuple, FlightRecordedEvent.OutputTuple, FlightRecordedEvent.OutputObject>;
getEvent(key: 'LicenseGranted'): TypedContractEvent<LicenseGrantedEvent.InputTuple, LicenseGrantedEvent.OutputTuple, LicenseGrantedEvent.OutputObject>;
getEvent(key: 'PilotRegistered'): TypedContractEvent<PilotRegisteredEvent.InputTuple, PilotRegisteredEvent.OutputTuple, PilotRegisteredEvent.OutputObject>;
getEvent(key: 'RequestApproved'): TypedContractEvent<RequestApprovedEvent.InputTuple, RequestApprovedEvent.OutputTuple, RequestApprovedEvent.OutputObject>;
getEvent(key: 'RequestCreated'): TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;

    filters: {
      
      'FlightRecorded(address,uint256)': TypedContractEvent<FlightRecordedEvent.InputTuple, FlightRecordedEvent.OutputTuple, FlightRecordedEvent.OutputObject>;
      FlightRecorded: TypedContractEvent<FlightRecordedEvent.InputTuple, FlightRecordedEvent.OutputTuple, FlightRecordedEvent.OutputObject>;
    

      'LicenseGranted(address,uint256,uint256)': TypedContractEvent<LicenseGrantedEvent.InputTuple, LicenseGrantedEvent.OutputTuple, LicenseGrantedEvent.OutputObject>;
      LicenseGranted: TypedContractEvent<LicenseGrantedEvent.InputTuple, LicenseGrantedEvent.OutputTuple, LicenseGrantedEvent.OutputObject>;
    

      'PilotRegistered(address,uint256)': TypedContractEvent<PilotRegisteredEvent.InputTuple, PilotRegisteredEvent.OutputTuple, PilotRegisteredEvent.OutputObject>;
      PilotRegistered: TypedContractEvent<PilotRegisteredEvent.InputTuple, PilotRegisteredEvent.OutputTuple, PilotRegisteredEvent.OutputObject>;
    

      'RequestApproved(uint256,address)': TypedContractEvent<RequestApprovedEvent.InputTuple, RequestApprovedEvent.OutputTuple, RequestApprovedEvent.OutputObject>;
      RequestApproved: TypedContractEvent<RequestApprovedEvent.InputTuple, RequestApprovedEvent.OutputTuple, RequestApprovedEvent.OutputObject>;
    

      'RequestCreated(address,address,uint256)': TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
      RequestCreated: TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
    
    };
  }