/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IRecoverableInterface extends Interface {
    getFunction(nameOrSignature: "addAdmin" | "setNewOwner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddAdmin" | "SetNewOwner"): EventFragment;

    encodeFunctionData(functionFragment: 'addAdmin', values: [BytesLike, BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setNewOwner', values: [BytesLike, BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setNewOwner', data: BytesLike): Result;
  }

  
    export namespace AddAdminEvent {
      export type InputTuple = [newAdmin: AddressLike];
      export type OutputTuple = [newAdmin: string];
      export interface OutputObject {newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetNewOwnerEvent {
      export type InputTuple = [newOwner: AddressLike];
      export type OutputTuple = [newOwner: string];
      export interface OutputObject {newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IRecoverable extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRecoverable;
    waitForDeployment(): Promise<this>;

    interface: IRecoverableInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAdmin: TypedContractMethod<
      [_newAdminSigned: BytesLike, _signature: BytesLike, _newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setNewOwner: TypedContractMethod<
      [_newOwnerSigned: BytesLike, _signature: BytesLike, _newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [_newAdminSigned: BytesLike, _signature: BytesLike, _newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setNewOwner'): TypedContractMethod<
      [_newOwnerSigned: BytesLike, _signature: BytesLike, _newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AddAdmin'): TypedContractEvent<AddAdminEvent.InputTuple, AddAdminEvent.OutputTuple, AddAdminEvent.OutputObject>;
getEvent(key: 'SetNewOwner'): TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;

    filters: {
      
      'AddAdmin(address)': TypedContractEvent<AddAdminEvent.InputTuple, AddAdminEvent.OutputTuple, AddAdminEvent.OutputObject>;
      AddAdmin: TypedContractEvent<AddAdminEvent.InputTuple, AddAdminEvent.OutputTuple, AddAdminEvent.OutputObject>;
    

      'SetNewOwner(address)': TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
      SetNewOwner: TypedContractEvent<SetNewOwnerEvent.InputTuple, SetNewOwnerEvent.OutputTuple, SetNewOwnerEvent.OutputObject>;
    
    };
  }